### PR TITLE
Consistency and cleanup

### PR DESCRIPTION
**Pull request by sideshowcoder**
Some test classes use both `spec` as well as `assert` syntax in the same file, this makes it quite awkward to work with and also the tests are not very well seperated. The goal of this PR is to start working towards a consistent structure for ease of development. Along those lines there are also some test which are not really easy to understand or rely on external state, so minimizing this while refactoring the tests is also a goal.

### CODE REVIEW

**Comment by nickcampbell18** [comment]
Yay Minitest! \o/ 👍

**Comment by yarmand** [comment]
all this test_xxx methods ... bye bye readibility ! 8-p

**Comment by sideshowcoder** [comment]
Well @yarmand feel free to port all the tests to spec ... but please all of them :tongue:

**Comment by yarmand** [comment]
I knew you would answer that ! 8-p

**Pull request merged**
