### PR TITLE
Require rest of Timer classes

### LINKED ISSUE #129: uninitialized constant Circuitbox::Timer::Null (NameError)
I'm getting this error on the latest pre version(2.0.0.pre1). It would seem that require_relative is missing for the other Timer classes.

### PR DESCRIPTION
**Pull request by Sija**
Fixes #129
Closes #130

### CODE REVIEW

**Comment by ritikesh** [comment]
I opened a PR(https://github.com/yammer/circuitbox/pull/130/files) for this almost 2 months back. Don't think the Yam folks care. 😄

**Comment by Sija** [comment]
@ritikesh Your PR changes more than that (aliasing), so in hope to make it a no-brainer decision, I've decided to open another one, with the changes strictly related to issue at hand.

**Comment by Sija** [comment]
@matthewshafer ping

**Comment by matthewshafer** [comment]
This should be fixed with #130. Thanks for pinging me though because that let me know my notification settings were removed (it's a long story).

**Pull request closed without merging**
