### PR TITLE
Handle circuit timing in the notifiers

### PR DESCRIPTION
**Pull request by matthewshafer**
Rather than Circuitbox handling the timing have the notifiers do it. For ActiveSupport it already returns the start and finish time when given a block. ActiveSupport::Notifications::Event can be used to easily access the duration. For the null timer it means no timing will be done.

### CODE REVIEW

**Comment by ritikesh** [comment]
Hey @matthewshafer - any ETAs on when this will be merged?

**Comment by matthewshafer** [comment]
@ritikesh I can push a release to rubygems during the day

**Comment by ritikesh** [comment]
thanks @matthewshafer for the quick turnaround!

**Comment by ritikesh** [comment]
@matthewshafer - any rough timelines on the rubygems push? We've been using the master branch in production, no issues so far.

**Pull request merged**
