### PR TITLE
Remove the hack that is partitions.

### PR DESCRIPTION
**Pull request by matthewshafer**
I'll admit that I don't know much about this or why it was added. I think "partitioning" circuit's can also be done by just creating more circuits and just have code decide which one to use.  @yarmand I think you know way more about this then I do, thoughts?

### CODE REVIEW

**Comment by sideshowcoder** [comment]
Yes please remove this this has been on the kill list for some time actually. Make sure to bum the version accordingly so as this breaks API. 👍

**Comment by yarmand** [comment]
Thanks for doing this ! (y)
I second Phil, please bump the version.

**Comment by matthewshafer** [comment]
I'll bump the major version up tonight.  I have some other changes relating to performance/memory optimization (another pr) so it'll be nice to be on a new major version with these changes.

**Comment by yarmand** [comment]
@matthewshafer do you know about version management rake tasks ?
```
rake version             # print current version
rake version:bump:major  # Bump the major version by 1
rake version:bump:minor  # Bump the minor version by 1
rake version:bump:patch  # Bump the patch version by 1
rake version:write       # write a specific version - example: rake version:write VERSION=1.2.3
```

**Comment by matthewshafer** [comment]
@yarmand Yes. But for pre-release versions it's about the same amount of work to manually set the version myself. At the same time I was able to fix up some indentation and spacing of the version constant.

**Pull request merged**
